server:  
  port: ${PORT:2222}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

  rabbitmq:
    host: localhost
    port: 30000
    username: guest
    password: guest
          
ribbon:
  eureka:
    enabled: true
    
test:
  accounts:
    - id: 1
      number: '0654321789'
      balance: 4550
      customerId: 1
    - id: 2
      number: '0654321780'
      balance: 40
      customerId: 1
    - id: 3
      number: '0650981789'
      balance: 22555
      customerId: 2